/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.30.1-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Bess.IO.Rest.Nexus3.Client.SwaggerDateConverter;

namespace Bess.IO.Rest.Nexus3.Model
{
    /// <summary>
    /// AptHostedRepositoriesAttributes
    /// </summary>
    [DataContract]
    public partial class AptHostedRepositoriesAttributes :  IEquatable<AptHostedRepositoriesAttributes>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AptHostedRepositoriesAttributes" /> class.
        /// </summary>
        /// <param name="distribution">Distribution to fetch.</param>
        public AptHostedRepositoriesAttributes(string distribution = default(string))
        {
            this.Distribution = distribution;
        }
        
        /// <summary>
        /// Distribution to fetch
        /// </summary>
        /// <value>Distribution to fetch</value>
        [DataMember(Name="distribution", EmitDefaultValue=false)]
        public string Distribution { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AptHostedRepositoriesAttributes {\n");
            sb.Append("  Distribution: ").Append(Distribution).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AptHostedRepositoriesAttributes);
        }

        /// <summary>
        /// Returns true if AptHostedRepositoriesAttributes instances are equal
        /// </summary>
        /// <param name="input">Instance of AptHostedRepositoriesAttributes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AptHostedRepositoriesAttributes input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Distribution == input.Distribution ||
                    (this.Distribution != null &&
                    this.Distribution.Equals(input.Distribution))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Distribution != null)
                    hashCode = hashCode * 59 + this.Distribution.GetHashCode();
                return hashCode;
            }
        }
    }

}
