/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.30.1-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Bess.IO.Rest.Nexus3.Client.SwaggerDateConverter;

namespace Bess.IO.Rest.Nexus3.Model
{
    /// <summary>
    /// GenericBlobStoreApiResponse
    /// </summary>
    [DataContract]
    public partial class GenericBlobStoreApiResponse :  IEquatable<GenericBlobStoreApiResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GenericBlobStoreApiResponse" /> class.
        /// </summary>
        /// <param name="softQuota">Settings to control the soft quota.</param>
        /// <param name="name">name.</param>
        /// <param name="type">type.</param>
        /// <param name="unavailable">unavailable.</param>
        /// <param name="blobCount">blobCount.</param>
        /// <param name="totalSizeInBytes">totalSizeInBytes.</param>
        /// <param name="availableSpaceInBytes">availableSpaceInBytes.</param>
        public GenericBlobStoreApiResponse(BlobStoreApiSoftQuota softQuota = default(BlobStoreApiSoftQuota), string name = default(string), string type = default(string), bool? unavailable = default(bool?), long? blobCount = default(long?), long? totalSizeInBytes = default(long?), long? availableSpaceInBytes = default(long?))
        {
            this.SoftQuota = softQuota;
            this.Name = name;
            this.Type = type;
            this.Unavailable = unavailable;
            this.BlobCount = blobCount;
            this.TotalSizeInBytes = totalSizeInBytes;
            this.AvailableSpaceInBytes = availableSpaceInBytes;
        }
        
        /// <summary>
        /// Settings to control the soft quota
        /// </summary>
        /// <value>Settings to control the soft quota</value>
        [DataMember(Name="softQuota", EmitDefaultValue=false)]
        public BlobStoreApiSoftQuota SoftQuota { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Unavailable
        /// </summary>
        [DataMember(Name="unavailable", EmitDefaultValue=false)]
        public bool? Unavailable { get; set; }

        /// <summary>
        /// Gets or Sets BlobCount
        /// </summary>
        [DataMember(Name="blobCount", EmitDefaultValue=false)]
        public long? BlobCount { get; set; }

        /// <summary>
        /// Gets or Sets TotalSizeInBytes
        /// </summary>
        [DataMember(Name="totalSizeInBytes", EmitDefaultValue=false)]
        public long? TotalSizeInBytes { get; set; }

        /// <summary>
        /// Gets or Sets AvailableSpaceInBytes
        /// </summary>
        [DataMember(Name="availableSpaceInBytes", EmitDefaultValue=false)]
        public long? AvailableSpaceInBytes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GenericBlobStoreApiResponse {\n");
            sb.Append("  SoftQuota: ").Append(SoftQuota).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Unavailable: ").Append(Unavailable).Append("\n");
            sb.Append("  BlobCount: ").Append(BlobCount).Append("\n");
            sb.Append("  TotalSizeInBytes: ").Append(TotalSizeInBytes).Append("\n");
            sb.Append("  AvailableSpaceInBytes: ").Append(AvailableSpaceInBytes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GenericBlobStoreApiResponse);
        }

        /// <summary>
        /// Returns true if GenericBlobStoreApiResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of GenericBlobStoreApiResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GenericBlobStoreApiResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SoftQuota == input.SoftQuota ||
                    (this.SoftQuota != null &&
                    this.SoftQuota.Equals(input.SoftQuota))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Unavailable == input.Unavailable ||
                    (this.Unavailable != null &&
                    this.Unavailable.Equals(input.Unavailable))
                ) && 
                (
                    this.BlobCount == input.BlobCount ||
                    (this.BlobCount != null &&
                    this.BlobCount.Equals(input.BlobCount))
                ) && 
                (
                    this.TotalSizeInBytes == input.TotalSizeInBytes ||
                    (this.TotalSizeInBytes != null &&
                    this.TotalSizeInBytes.Equals(input.TotalSizeInBytes))
                ) && 
                (
                    this.AvailableSpaceInBytes == input.AvailableSpaceInBytes ||
                    (this.AvailableSpaceInBytes != null &&
                    this.AvailableSpaceInBytes.Equals(input.AvailableSpaceInBytes))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SoftQuota != null)
                    hashCode = hashCode * 59 + this.SoftQuota.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.Unavailable != null)
                    hashCode = hashCode * 59 + this.Unavailable.GetHashCode();
                if (this.BlobCount != null)
                    hashCode = hashCode * 59 + this.BlobCount.GetHashCode();
                if (this.TotalSizeInBytes != null)
                    hashCode = hashCode * 59 + this.TotalSizeInBytes.GetHashCode();
                if (this.AvailableSpaceInBytes != null)
                    hashCode = hashCode * 59 + this.AvailableSpaceInBytes.GetHashCode();
                return hashCode;
            }
        }
    }

}
